"""Tier-3 smoke: the PR 3 foundation commands on Claude Code.

One test per command — `gen-world`, `gen-characters`, `gen-outline`,
`voice-discovery`, `gen-canon`. Each starts from a copy of the
`tiny-series-historical` fixture with the command's write target reset
to the template placeholder, runs the real runtime, and asserts the
acceptance block from the corresponding `commands/*.md`.

Opt-in under `@pytest.mark.smoke`. Skips cleanly when `claude` is not on
`$PATH` (see `tests/smoke/conftest.py`). Subscription auth is primary;
the conftest strips `ANTHROPIC_API_KEY` unless `AUTONOVEL_SMOKE_USE_API_KEY=1`.

These are cheap-ish (each command is one model call), but still real
spend. Run individually with `-k gen_world` etc. when iterating.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from .conftest import run_command_in_runtime


PLACEHOLDER_WORLD = "# World\n\n<!-- Generated by /autonovel:gen-world. Leave empty until then. -->\n"
PLACEHOLDER_CHARACTERS = (
    "# Characters\n\n<!-- Generated by /autonovel:gen-characters. Leave empty until then. -->\n"
)
PLACEHOLDER_OUTLINE = "# Outline\n\n<!-- Generated by /autonovel:gen-outline. Leave empty until then. -->\n"
PLACEHOLDER_VOICE_PART2 = (
    "# Voice\n\n"
    "## Part 1 — Series voice\n"
    "Close third, past tense. Period-accurate to 1520 Venice in vocabulary and\n"
    "sensibility; avoid modern idiom or clinical 21st-century observations.\n\n"
    "## Part 2 — Book fingerprint\n\n"
    "<!-- Filled by /autonovel:voice-discovery. Leave empty until then. -->\n"
)
PLACEHOLDER_CANON = (
    "# Canon\n\n"
    "Hard facts true across all books in this series. Each entry is a single\n"
    "verifiable claim; commands reference it by the headline in brackets.\n\n"
    "<!-- Seeded by /autonovel:gen-canon; grown by /autonovel:promote-canon. -->\n"
)


def _word_count(text: str) -> int:
    body = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)
    return len(body.split())


@pytest.mark.smoke
@pytest.mark.genre("historical")
def test_gen_world(tmp_runtime_series) -> None:
    series = tmp_runtime_series("tiny-series-historical")
    target = series.path / "shared" / "world.md"
    target.write_text(PLACEHOLDER_WORLD, encoding="utf-8")

    result = run_command_in_runtime(
        runtime="claude",
        command="/autonovel:gen-world",
        cwd=series.path,
        allowed_tools=["Read", "Write", "Bash"],
    )
    assert result.returncode == 0, (
        f"claude returned {result.returncode}\nstdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )

    text = target.read_text(encoding="utf-8")
    assert text.lstrip().startswith("# World"), "missing top-level heading"
    assert _word_count(text) >= 400, f"world body too short: {_word_count(text)} words"
    # Not just the placeholder left over.
    assert "Generated by /autonovel:gen-world" not in text or _word_count(text) >= 400


@pytest.mark.smoke
@pytest.mark.genre("historical")
def test_gen_characters(tmp_runtime_series) -> None:
    series = tmp_runtime_series("tiny-series-historical")
    target = series.path / "shared" / "characters.md"
    target.write_text(PLACEHOLDER_CHARACTERS, encoding="utf-8")

    result = run_command_in_runtime(
        runtime="claude",
        command="/autonovel:gen-characters",
        cwd=series.path,
        allowed_tools=["Read", "Write", "Bash"],
    )
    assert result.returncode == 0, (
        f"claude returned {result.returncode}\nstdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )

    text = target.read_text(encoding="utf-8")
    assert text.lstrip().startswith("# Characters"), "missing top-level heading"
    # Every POV from project.yaml must appear by name.
    assert "Tommaso" in text, "POV `Tommaso` missing from roster"


@pytest.mark.smoke
@pytest.mark.genre("historical")
def test_gen_outline(tmp_runtime_series) -> None:
    series = tmp_runtime_series("tiny-series-historical")
    target = series.path / "books" / "tiny-inquisitor" / "outline.md"
    target.write_text(PLACEHOLDER_OUTLINE, encoding="utf-8")

    result = run_command_in_runtime(
        runtime="claude",
        command="/autonovel:gen-outline --book tiny-inquisitor",
        cwd=series.path,
        allowed_tools=["Read", "Write", "Bash"],
    )
    assert result.returncode == 0, (
        f"claude returned {result.returncode}\nstdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )

    text = target.read_text(encoding="utf-8")
    assert text.lstrip().startswith("# Outline"), "missing top-level heading"
    chapters = re.findall(r"^## Chapter \d+", text, flags=re.MULTILINE)
    assert len(chapters) >= 3, f"need at least 3 chapter headings; got {len(chapters)}"
    assert "story_time" in text, "outline entries must carry story_time"
    assert "beats" in text, "outline entries must list beats"


@pytest.mark.smoke
@pytest.mark.genre("historical")
def test_voice_discovery(tmp_runtime_series) -> None:
    series = tmp_runtime_series("tiny-series-historical")
    target = series.path / "books" / "tiny-inquisitor" / "voice.md"
    target.write_text(PLACEHOLDER_VOICE_PART2, encoding="utf-8")

    result = run_command_in_runtime(
        runtime="claude",
        command="/autonovel:voice-discovery --book tiny-inquisitor",
        cwd=series.path,
        allowed_tools=["Read", "Write", "Bash"],
    )
    assert result.returncode == 0, (
        f"claude returned {result.returncode}\nstdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )

    text = target.read_text(encoding="utf-8")
    assert "## Part 1" in text, "Part 1 must be preserved verbatim"
    assert "Close third, past tense" in text, "Part 1 contents dropped"
    assert "## Part 2" in text, "Part 2 heading missing"
    # Part 2 body must not be only the placeholder comment.
    part2 = text.split("## Part 2", 1)[1]
    body = re.sub(r"<!--.*?-->", "", part2, flags=re.DOTALL).strip()
    assert body, "Part 2 is empty after voice-discovery"
    assert len(body.split()) >= 40, f"Part 2 is too short: {len(body.split())} words"


@pytest.mark.smoke
@pytest.mark.genre("historical")
def test_gen_canon(tmp_runtime_series) -> None:
    series = tmp_runtime_series("tiny-series-historical")
    target = series.path / "shared" / "canon.md"
    target.write_text(PLACEHOLDER_CANON, encoding="utf-8")

    result = run_command_in_runtime(
        runtime="claude",
        command="/autonovel:gen-canon",
        cwd=series.path,
        allowed_tools=["Read", "Write", "Bash"],
    )
    assert result.returncode == 0, (
        f"claude returned {result.returncode}\nstdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )

    text = target.read_text(encoding="utf-8")
    assert text.lstrip().startswith("# Canon"), "missing top-level heading"
    bullets = [ln for ln in text.splitlines() if ln.strip().startswith("- ")]
    assert len(bullets) >= 3, f"need at least 3 canon bullets; got {len(bullets)}"


@pytest.mark.smoke
@pytest.mark.genre("historical")
def test_sidequest_menu_is_read_only(tmp_runtime_series) -> None:
    """Sidequest dispatcher must not write files. Contract rather than cost.

    We can't interactively pick an option from a subprocess, but we can
    verify the menu prints and no write targets are touched.
    """
    series: Path = tmp_runtime_series("tiny-series-historical").path
    before = _snapshot(series)

    result = run_command_in_runtime(
        runtime="claude",
        command="/autonovel:sidequest",
        cwd=series,
        allowed_tools=["Read", "Bash"],
        timeout=180,
    )
    # Non-interactive `claude -p` exits after one turn; we only care that
    # the run was clean and nothing changed on disk.
    assert result.returncode == 0, (
        f"claude returned {result.returncode}\nstdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )
    assert "gen-world" in result.stdout or "gen-world" in result.stderr, (
        "menu did not list foundation commands"
    )
    after = _snapshot(series)
    assert before == after, "sidequest dispatcher modified files (must be read-only)"


def _snapshot(root: Path) -> dict[str, bytes]:
    """Cheap content snapshot for read-only assertion. Ignores .autonovel/."""
    out: dict[str, bytes] = {}
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        # `.autonovel/command-log.jsonl` gets appended even for read-only
        # commands (via the postamble); that's lifecycle bookkeeping, not a
        # content write. Exclude the whole `.autonovel/` tree from the
        # "must not change" assertion.
        if rel.parts and rel.parts[0] == ".autonovel":
            continue
        out[str(rel)] = p.read_bytes()
    return out
